#!/bin/bash

IFILE=""

PLOT_PURE=0
PLOT_MIXED=1

# Retorna una lista a dos columnas con las lineas de absorción
getColumnsLines(){
	local iFile=$1
	awk '($1~/#/){print $2,$3}' $iFile
}

# Retorna una lista a dos columnas con el espectro
getColumnsSpec(){
	local iFile=$1
	awk '
		BEGIN{
			locBlank=0
			loc=0
		}
		{
			if( locBlank==1 && $0~/^[[:blank:]]*$/ ){
				loc=0
			}
			
			if( loc==1 )
				print $0
				
			if( locBlank==1 && $0~/^[[:blank:]]*$/ ){
				loc=1
			}
			
			if( $0~/^[[:blank:]]*$/ ){
				locBlank=1
			}else{
				locBlank=0
			}
		}
	' $iFile
}

plotSpectraZ()
{
	join -j 1 ${IFILE}PureSpecO.dat ${IFILE}PureSpecP.dat > .tmpJoin1 2> /dev/null
	join -j 1 ${IFILE}PureSpecQ.dat ${IFILE}PureSpecR.dat > .tmpJoin2 2> /dev/null
	join -j 1 .tmpJoin1 .tmpJoin2 > .tmpJoin3 2> /dev/null
	join -j 1 ${IFILE}PureSpecS.dat .tmpJoin3 > .tmpJoin4 2> /dev/null
	awk '($1!~/^#/){ sum=0.0; for(i=2;i<=NF;i++) sum+=$i; print $1,sum }' .tmpJoin4 > ${IFILE}PureSpecTotal.dat
	
	join -j 1 ${IFILE}MixedSpecO.dat ${IFILE}MixedSpecP.dat > .tmpJoin1 2> /dev/null
	join -j 1 ${IFILE}MixedSpecQ.dat ${IFILE}MixedSpecR.dat > .tmpJoin2 2> /dev/null
	join -j 1 .tmpJoin1 .tmpJoin2 > .tmpJoin3 2> /dev/null
	join -j 1 ${IFILE}MixedSpecS.dat .tmpJoin3 > .tmpJoin4 2> /dev/null
	awk '($1!~/^#/){ sum=0.0; for(i=2;i<=NF;i++) sum+=$i; print $1,sum }' .tmpJoin4 > ${IFILE}MixedSpecTotal.dat
	
	rm -rf .tmpJoin*
	
	gnuplot -p << EOF
set termopt enhanced
set encoding iso_8859_1

unset ytics
unset key
set border 1 lw 2.0

# set size square
set size 0.4,1.0

set xlabel "Energy lost ( cm^{-1} )" font "Serif,12" #offset 0.0,0.5

set mxtics 5
unset label

set samples 50000

set format x "%3.3f"
set xtics 0.01 out nomirror font "Serif,10"

set y2range [:$Y2MAX]

# 	plot [-0.07:-0.02] []
# 	plot [1.37:1.42] []
# 	plot [-0.03: 0.00] [] N=1
# 	plot [-0.04:-0.01] [] N=2
# 	plot [-0.05:-0.01] [] N=3
# 	plot [0.45:0.49] [] N=1 zoom mixed

if ( $PLOT_PURE ) \
	plot [-0.03:0.01] [] \
	"${IFILE}PureSpecQ.dat" i 0 u 1:(\$2) axis x1y2 t "Q-branch" w l lw 1.5 lc rgb "red", \
	"${IFILE}PureSpecQ.dat" i 1 u 1:(\$2) t "Q-branch" w l lw 2.5 lc rgb "red", \
	"${IFILE}PureSpecS.dat" i 0 u 1:(\$2*2.0) axis x1y2 t "S-branch" w l lw 1.5 lc rgb "cyan", \
	"${IFILE}PureSpecR.dat" i 0 u 1:(\$2*3.0) axis x1y2 t "R-branch" w l lw 1.5 lc rgb "blue", \
	"${IFILE}PureSpecP.dat" i 0 u 1:(\$2*8.0) axis x1y2 t "P-branch" w l lw 1.5 lc rgb "orange", \
	"${IFILE}PureSpecO.dat" i 0 u 1:(\$2*15.0) axis x1y2 t "O-branch" w l lw 1.5 lc rgb "forest-green"; \
else if ( $PLOT_MIXED ) \
	plot [-0.05:-0.03] [] \
	"${IFILE}MixedSpecQ.dat" i 0 u 1:(\$2) axis x1y2 t "Q-branch" w l lw 1.5 lc rgb "red", \
	"${IFILE}MixedSpecQ.dat" i 1 u 1:(\$2) t "Q-branch" w l lw 2.5 lc rgb "red", \
	"${IFILE}MixedSpecS.dat" i 0 u 1:(\$2*2.0) axis x1y2 t "S-branch" w l lw 1.5 lc rgb "cyan", \
	"${IFILE}MixedSpecR.dat" i 0 u 1:(\$2*3.0) axis x1y2 t "R-branch" w l lw 1.5 lc rgb "blue", \
	"${IFILE}MixedSpecP.dat" i 0 u 1:(\$2*8.0) axis x1y2 t "P-branch" w l lw 1.5 lc rgb "orange", \
	"${IFILE}MixedSpecO.dat" i 0 u 1:(\$2*15.0) axis x1y2 t "O-branch" w l lw 1.5 lc rgb "forest-green";

EOF
}

plotSpectra()
{
	join -j 1 ${IFILE}PureSpecO.dat ${IFILE}PureSpecP.dat > .tmpJoin1 2> /dev/null
	join -j 1 ${IFILE}PureSpecQ.dat ${IFILE}PureSpecR.dat > .tmpJoin2 2> /dev/null
	join -j 1 .tmpJoin1 .tmpJoin2 > .tmpJoin3 2> /dev/null
	join -j 1 ${IFILE}PureSpecS.dat .tmpJoin3 > .tmpJoin4 2> /dev/null
	awk '($1!~/^#/){ sum=0.0; for(i=2;i<=NF;i++) sum+=$i; print $1,sum }' .tmpJoin4 > ${IFILE}PureSpecTotal.dat
	
	join -j 1 ${IFILE}MixedSpecO.dat ${IFILE}MixedSpecP.dat > .tmpJoin1 2> /dev/null
	join -j 1 ${IFILE}MixedSpecQ.dat ${IFILE}MixedSpecR.dat > .tmpJoin2 2> /dev/null
	join -j 1 .tmpJoin1 .tmpJoin2 > .tmpJoin3 2> /dev/null
	join -j 1 ${IFILE}MixedSpecS.dat .tmpJoin3 > .tmpJoin4 2> /dev/null
	awk '($1!~/^#/){ sum=0.0; for(i=2;i<=NF;i++) sum+=$i; print $1,sum }' .tmpJoin4 > ${IFILE}MixedSpecTotal.dat
	
	rm -rf .tmpJoin*
	
	gnuplot -p << EOF
set termopt enhanced
set encoding iso_8859_1

unset ytics
unset key
set border 1 lw 2.0

# set size square
set size 0.4,1.0
# set size 0.8,1.0

set xlabel "Energy lost ( cm^{-1} )" font "Serif,12" #offset 0.0,0.5

set mxtics 5
unset label

set samples 50000

set format x "%3.1f"
set xtics 2.0 out nomirror font "Serif,10"

set y2range [:30.0]

if ( $PLOT_PURE ) \
	plot [-2:8] [] \
	"${IFILE}PureSpecQ.dat" i 1 u 1:(\$2) t "Q-branch" w l lw 2.0 lc rgb "red", \
	"${IFILE}PureSpecS.dat" i 1 u 1:(\$2*2.0) t "S-branch" w l lw 2.0 lc rgb "cyan", \
	"${IFILE}PureSpecR.dat" i 1 u 1:(\$2*3.0) t "R-branch" w l lw 2.0 lc rgb "blue", \
	"${IFILE}PureSpecP.dat" i 1 u 1:(\$2*8.0) t "P-branch" w l lw 2.0 lc rgb "orange", \
	"${IFILE}PureSpecO.dat" i 1 u 1:(\$2*15.0) t "O-branch" w l lw 2.0 lc rgb "forest-green"; \
else if ( $PLOT_MIXED ) \
	plot [-2:8] [] \
	"${IFILE}MixedSpecQ.dat" i 1 u 1:(\$2) t "Q-branch" w l lw 2.0 lc rgb "red", \
	"${IFILE}MixedSpecS.dat" i 1 u 1:(\$2*2.0) t "S-branch" w l lw 2.0 lc rgb "cyan", \
	"${IFILE}MixedSpecR.dat" i 1 u 1:(\$2*3.0) t "R-branch" w l lw 2.0 lc rgb "blue", \
	"${IFILE}MixedSpecP.dat" i 1 u 1:(\$2*8.0) t "P-branch" w l lw 2.0 lc rgb "orange", \
	"${IFILE}MixedSpecO.dat" i 1 u 1:(\$2*15.0) t "O-branch" w l lw 2.0 lc rgb "forest-green";

EOF
}

main()
{
	while getopts "i:pmy:zs" OPTNAME
	do
		case $OPTNAME in
			"i" )
				IFILE=${OPTARG%.*}
				;;
			"p" )
				PLOT_PURE=1
				PLOT_MIXED=0
				;;
			"m" )
				PLOT_PURE=0
				PLOT_MIXED=1
				;;
			"y" )
				Y2MAX=$OPTARG
				;;
			"z" )
				plotSpectraZ
				;;
			"s" )
				plotSpectra
				;;
			* )
				echo "@@ WARNING @@ Unknown parameter $command"
				;;
		esac
	done
	
	if [ -z "$IFILE" ]
	then
		echo "Usage:"
		echo "      $ plotSpectra.sh -i iFile.inp [ -p | -m ] [-y y2Max] [ -z | -s ]"
		exit
	fi
}

main $*
